//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGioiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucSP
    {
        public DanhMucSP()
        {
            this.KhuyenMais = new HashSet<KhuyenMai>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
