//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGioiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDHs = new HashSet<ChiTietDH>();
        }
    
        public int MaDonHang { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
    
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TrangThaiDonHang TrangThaiDonHang { get; set; }
    }
}
