//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGioiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public GioHang()
        {
            this.ChiTietGHs = new HashSet<ChiTietGH>();
        }
    
        public int MaGioHang { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
    
        public virtual ICollection<ChiTietGH> ChiTietGHs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
