//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGioiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int MaKM { get; set; }
        public string MaGiamGia { get; set; }
        public Nullable<int> PhanTramGiam { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> LoaiKhuyenMai { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        public virtual DanhMucSP DanhMucSP { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
