//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGioiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDHs = new HashSet<ChiTietDH>();
            this.ChiTietGHs = new HashSet<ChiTietGH>();
            this.DanhGias = new HashSet<DanhGia>();
            this.KhuyenMais = new HashSet<KhuyenMai>();
        }
    
        public int MaSanPham { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public bool IsShow { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        public virtual ICollection<ChiTietGH> ChiTietGHs { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DanhMucSP DanhMucSP { get; set; }
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
        public virtual TrangThaiSanPham TrangThaiSanPham { get; set; }
    }
}
